version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.289.3-lts-jdk11
    ports:
    - "8080:8080"
    volumes:
    - $PWD/jenkins_home:/var/jenkins_home
    networks:
    - jenkins_net
networks:
  jenkins_net:
