version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.289.3-lts-jdk11
    ports:
    - 8080:8080
    volumes:
    - $PWD/jenkins_home:/var/jenkins_home
    networks:
    - net
  remote-host:
    container_name: remote-host
    image: centos7
    networks:
    - net
  db-host:
    container_name: db-host
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    volumes:
    - $PWD/db_data:/var/lib/mysql
    networks:
    - net
networks:
  net:
