version: '2'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    ports:
    - 8080:8080
    volumes:
    - $PWD/jenkins_home:/var/jenkins_home
    networks:
    - net
  remote-host:
    container_name: remote-host
    image: centos7
    volumes:
    - $PWD/db-dump.sh:/tmp/db-dump.sh
    networks:
    - net
  db-host:
    container_name: db-host
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    volumes:
    - $PWD/db_data:/var/lib/mysql
    networks:
    - net
  web-host:
    container_name: web-host
    image: centos7-web
    ports:
    - 9090:9090
    networks:
    - net
  git-host:
    container_name: git-host
    mem_limit: 4G
    image: gitlab/gitlab-ce:14.1.3-ce.0
    hostname: 'gitlab.example.com'
    ports:
    - 8090:80
    volumes:
    - $PWD/gitlab/config:/etc/gitlab
    - $PWD/gitlab/logs:/var/log/gitlab
    - $PWD/gitlab/data:/var/opt/gitlab
    networks:
    - net
networks:
  net:
